[hugoVersion]
  extended = true
  min = "0.80.0"
  max = ""

[[mounts]]
  source = "node_modules/@hyas/doks/archetypes"
  target = "archetypes"

[[mounts]]
  source = "node_modules/@hyas/doks/assets"
  target = "assets"

#  [[mounts]]
#    source = "node_modules/@hyas/doks/content"
#    target = "content"

[[mounts]]
  source = "node_modules/@hyas/doks/data"
  target = "data"

[[mounts]]
  source = "node_modules/@hyas/doks/layouts"
  target = "layouts"

[[mounts]]
  source = "node_modules/@hyas/doks/static"
  target = "static"

[[mounts]]
  source = "node_modules/flexsearch"
  target = "assets/js/vendor/flexsearch"

[[mounts]]
  source = "node_modules/katex"
  target = "assets/js/vendor/katex"

[[mounts]]
  source = "node_modules/mermaid"
  target = "assets/js/vendor/mermaid"

[[mounts]]
  source = "assets"
  target = "assets"

[[mounts]]
  source = "static"
  target = "static"

#  [[mounts]]
#    source = "content"
#    target = "content"

[[mounts]]
  source = "layouts"
  target = "layouts"

[[mounts]]
  source = "archetypes"
  target = "archetypes"

[[mounts]]
  source = "data"
  target = "data"

[[mounts]]
  source = "node_modules/@hyas/images/layouts"
  target = "layouts"
