[[docs]]
  name = "Overview"
  weight = 10
  identifier = "overview"
  url = "/docs/overview/"

[[docs]]
  name = "Help"
  weight = 60
  identifier = "help"
  url = "/docs/help/"

# [[docs]]
#   name = "Lorem"
#   weight = 70
#   identifier = "lorem"
#   url = "/docs/lorem/"


[[main]]
  name = "Documentation"
  identifier = "docs"
  url = "/docs/overview/introduction/"
  weight = 10

[[main]]
  name = "Introduction"
  weight = 11
  url = "/docs/overview/introduction"
  parent = "docs"

[[main]]
  name = "Quick Start"
  weight = 12
  url = "/docs/overview/introduction"
  parent = "docs"

[[main]]
  name = "Install"
  weight = 13
  url = "/docs/how-to/install"
  parent = "docs"

[[main]]
  name = "Send messages"
  weight = 14
  url = "/docs/how-to/send-messages"
  parent = "docs"

[[main]]
  name = "Receive Messages"
  weight = 15
  url = "/docs/how-to/receive-messages"
  parent = "docs"

[[main]]
  name = "How to guides"
  weight = 20
  url = "/docs/how-to"
  parent = "docs"

[[main]]
  name = "Swagger ->"
  weight = 98
  url = "https://waha.devlike.pro/swagger"
  parent = "docs"

[[main]]
  name = "OpenAPI JSON ->"
  weight = 99
  url = "https://waha.devlike.pro/swagger/openapi.json"
  parent = "docs"

[[main]]
  name = "WAHA Plus"
  weight = 20
  identifier = "waha-plus"

[[main]]
  name = "About WAHA Plus"
  weight = 10
  url = "/docs/how-to/plus-version"
  parent = "waha-plus"

[[main]]
  name = "Patron Portal ->"
  weight = 20
  url = "https://portal.devlike.pro/"
  parent = "waha-plus"

[[main]]
  name = "Get on Patreon ->"
  weight = 60
  url = "https://patreon.com/wa_http_api"
  parent = "waha-plus"

[[main]]
  name = "Get on Boosty ->"
  weight = 50
  url = "https://boosty.to/wa-http-api"
  parent = "waha-plus"

[[main]]
  name = "Pricing"
  weight = 90
  url = "/pricing"


[[main]]
  name = "Examples"
  weight = 30
  identifier = "examples"

[[main]]
  name = "Python ->"
  weight = 31
  url = "/docs/examples/python"
  parent = "examples"

[[main]]
  name = "Kotlin ->"
  weight = 32
url = "/docs/examples/kotlin"
  parent = "examples"

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/devlikeapro/whatsapp-http-api"
  post = "v0.1.0"
  weight = 10

#[[social]]
#  name = "Twitter"
#  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
#  url = "https://twitter.com/getdoks"
#  weight = 20

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
